# Base settings from Blogger
# Minimal Mistakes Jekyll Theme Configuration

# Theme settings
theme                    : "minimal-mistakes-jekyll"
minimal_mistakes_skin    : "default"
remote_theme            : "mmistakes/minimal-mistakes@4.24.0"

# Site Settings
locale                   : "en-US"
title                    : "Sanjay Singh's Blog"
title_separator          : "-"
subtitle                 : "An another perspective"
name                     : "Sanjay Singh"
description              : "Sanjay Singh's Blog. Sharing my thoughts and experiences."
url                      : "https://blog.sanjaysingh.net"
baseurl                  : "/blog"
repository               : "sanjaysingh/blog"
teaser                   : # path of fallback teaser image
logo                     : # path of logo image to display in the masthead
masthead_title           : # overrides the website title displayed in the masthead
breadcrumbs              : true
words_per_minute         : 200
search                   : true

# Site Author
author:
  name             : "Author"
  avatar           : # path of avatar image
  bio              : ""
  location         : ""
  email            : ""
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sanjaysingh"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:year/:month/:day/:title/
paginate: 10
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      show_date: true
      comments: false
      share: true
      related: true
      classes: wide
